### ISSUE TITLE
Implement the Request endpoint

### ISSUE THREAD

**Issue by ahmetabdi** [sishen/uber-ruby#1]
https://devblog.uber.com/take-your-users-for-a-spin/

https://developer.uber.com//v1/endpoints/#request

**Comment by joshuaNathaniel** [comment]
:+1:  WIP?

**Comment by ahmetabdi** [comment]
Can do if nobody else is :yum:

**Comment by joshuaNathaniel** [comment]
@ahmetabdi  fork it?

**Comment by dylanjha** [comment]
@ahmetabdi have you started on this?

I'm looking through the code, it's a little unfortunate that the constant `Uber::Request` already exists. I think it should be renamed so that the Request resource can use that name.  How about `Uber::ApiRequest`?

It would be nice to add some tests to this gem. @sishen  do you have a preference for testing libraries/strategies? I personally would use [rspec](https://github.com/rspec/rspec) and [vcr](https://github.com/vcr/vcr) for this project.

**Comment by sishen** [comment]
@dylanjha @ahmetabdi Thank you, sorry that I don't have time to work on it. Feel free to change `Uber::Request` to `Uber::ApiRequest`. And both rspec and vcr are good to me.

**Comment by joshuaNathaniel** [comment]
Anyone making any headway on this? If not then in about a week I will have time to do.

**Comment by dylanjha** [comment]
I have not started on this.  Go for it @joshuaNathaniel

**Comment by joshuaNathaniel** [comment]
Will do.

**Comment by arunthampi** [comment]
Done here: https://github.com/sishen/uber-ruby/pull/5
